INSERT INTO STUDENT (NAME,CATS,PLACE) VALUES ('Alice',    300, 'Auburn'    );
INSERT INTO STUDENT (NAME,CATS,PLACE) VALUES ('Bob',      200, 'Brentwood' );
INSERT INTO STUDENT (NAME,CATS,PLACE) VALUES ('Cheyenne', 100, 'California');
INSERT INTO STUDENT (NAME,CATS,PLACE) VALUES ('Dora',      50, 'Dallas'    );
INSERT INTO STUDENT (NAME,CATS,PLACE) VALUES ('Eddie',     25, 'Emeryville');
INSERT INTO STUDENT (NAME,CATS,PLACE) VALUES ('Frank',     10, 'Fresno'    );